---
golang_path: "/home/{{ lookup('env', 'USER') }}/.local/go"
golang_install_path: "/home/{{ lookup('env', 'USER') }}/.local"
golang_installer_url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
golang_installer_temp_dest: "/tmp/golang-installer.tar.gz"
